version: '{branch}-{build}'
configuration: Release
clone_depth: 1
environment:
  matrix:
  - CMAKE_GEN: Visual Studio 17 2022 Win64
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
    BOOST: C:\Libraries\boost_1_77_0
  - CMAKE_GEN: Visual Studio 12 2013
    BOOST: C:\Libraries\boost_1_63_0
cache:
- C:\ProgramData\chocolatey\bin
- C:\ProgramData\chocolatey\lib
build_script:
- cmd: >-
    IF NOT EXIST C:\ProgramData\chocolatey\bin\swig.exe choco install --version 4.0.1 swig -y --limit-output
    cmake -D BOOST_ROOT=%BOOST% -G "%CMAKE_GEN%" .
    cmake --build . --config Release --target install
test_script:
- cmd: >-
    set path=%cd%\inst\bin;%path%
    ctest -C Release -V
artifacts:
- path: inst
