#!/bin/bash 
# $Id$

version=0.7.3
WEB="iris:/d2/people/wojdyr/www/fityk2/" 
TEMP_DOWNLOAD=$WEB/d/
SF_NEW_RELEASE="https://sourceforge.net/project/admin/newrelease.php?package_id=80864&group_id=79434"
SF_ADMIN_PAGE="https://sourceforge.net/project/admin/?group_id=79434"
WEB_ANNOUNCE_DIR=$WEB
WEB_ANNOUNCE_FILE="index.html"

BUILD_DIR=testbuild
CVSTEST_DIR=cvs_test
GCCX_DIR=gccx
OLDWX_DIR=oldwx
MINGW_DIR=cross_win32
ALL_WIN_FILES=all_files #inside of $MINGW_DIR

win_setup_filename=fityk-$version-setup.exe
tarball_filename=fityk-$version.tar.bz2

if [ $# -eq 0 ]; then 
 echo Version in this script is set to $version
 echo usage: $0 step_nr
 echo steps:
 echo 0. prepare new version and increase version number 
 echo "1. test if everything compiles after distclean, run samples"
 echo "2. test if this release can be compiled with other settings"
 echo "3. test if it compiles with older wxWidgets"
 echo "4. test if CVS version compiles"
 echo 5. put docs on www
 echo 6. compile windows version and make installer
 echo 7. uploading to local server, for testing on other computers
 echo 8. SourceForge release
 echo 9. web announce
 echo 10. FreshMeat announce
 echo 11. clean all changes... 
 exit
fi

echo
echo        Step $1 of the release procedure...         
echo
echo -n '===>' 



if [ $1 -eq 0 ]; then
 echo increase version number in configure.ac
 echo "please do it!  See the line with AM_INIT_AUTOMAKE(fityk, x.y.z)"
 echo "and the line with version=x.x.x in this release script"
 echo
 echo now the version in this script is: $version
 echo and configure.ac contains:
 grep AM_INIT_AUTOMAKE configure.ac



elif [ $1 -eq 1 ]; then
 echo  testing compilation and instalation after make distclean

 make distclean
 ./autogen.sh
 rm -rf $BUILD_DIR
 mkdir $BUILD_DIR
 cd $BUILD_DIR
 ../configure --prefix=$HOME/local
 make 
 make dist-bzip2
 mv $tarball_filename ..
 make install
 echo run samples...
 cd ../samples
 cfityk nacl01.fit 
 fityk nacl01.fit
 fityk SiC_Zn.fit



elif [ $1 -eq 2 ]; then
 echo  testing compilation with gcc 3.3 and --wx-config=/usr/bin/wx-config
 rm -rf $GCCX_DIR
 mkdir $GCCX_DIR
 cd $GCCX_DIR
 tar xjf ../$tarball_filename
 cd fityk-$version  
 CC=gcc-3.3 CXX=g++-3.3 ./configure --wx-config=/usr/bin/wx-config
 make
 ls -l src/fityk src/cfityk
 cd ../..
 

elif [ $1 -eq 3 ]; then
 OLD_WXCONFIG=wxgtk-2.4-config
 echo test other wx version
 #mv -i $HOME/local $HOME/Local
 echo Testing with version `$OLD_WXCONFIG --version`
 rm -rf $OLDWX_DIR
 mkdir $OLDWX_DIR
 cd $OLDWX_DIR
 ../configure --with-wx-config=$OLD_WXCONFIG
 cd src
 make
 ./fityk
 #mv -i $HOME/Local $HOME/local

elif [ $1 -eq 4 ]; then
 echo  testing downloading and building CVS version 
 rm -rf $CVSTEST_DIR
 mkdir $CVSTEST_DIR
 cd $CVSTEST_DIR
 echo "anonymous login to CVS..."
 cvs -d:pserver:anonymous@cvs.sourceforge.net:/cvsroot/fityk login
 cvs -z3 -d:pserver:anonymous@cvs.sourceforge.net:/cvsroot/fityk co fityk
 cd fityk
 ./autogen.sh
 ./configure
 make 
 

 
elif [ $1 -eq 5 ]; then
 echo  putting docs on www   
 echo destination: $WEB
 echo sending fitykhelp.html fitykhelp.xml ...
 cd doc/ 
 scp fitykhelp.html fitykhelp.xml $WEB/doc/
 echo sending fitykhelp_img ...
 scp -r fitykhelp_img/ $WEB/doc/
 echo generating html chunks...
 xmlto html fitykhelp.xml
 echo sending html chunks...
 scp *.html $WEB/doc/html/
 cd ..
 echo sending NEWS file...
 scp NEWS $WEB/d/
 echo generating doxygen docs...
 cd doxygen/
 doxygen
 echo sending doxygen docs... 
 scp -r html/ $WEB/doxygen/
 cd ..
 
 
 
elif [ $1 -eq 6 ]; then
 echo Building MS Windows version
 WXMSWINSTALL=/home/wojdyr/local/mingw32msvc/
 #
 # wxWidgets where cross-compiled using debian mingw32* packages:
 #      download wxAll
 #      tar xjf ../tarballs/wxWidgets-2.6.2.tar.bz2
 #      cd wxWidgets-2.6.2/
 #      mkdir build-mingw
 #      cd build-mingw/
 #      ../configure --build=i686-pc-linux-gnu --host=i586-mingw32msvc \
 #        --with-msw --disable-threads --disable-shared --disable-unicode \
 #        --enable-optimise --prefix=$WXMSWINSTALL \
 #        --without-regex --without-expat --without-odbc \
 #        --without-opengl --without-libjpeg --without-libtiff 
 #      # last 2 lines are not neccessary, but fityk is not using these features
 #      # and we don't have to build it.
 #      make; make install
 #
 rm -rf $MINGW_DIR
 mkdir $MINGW_DIR
 cd $MINGW_DIR
 ../configure --build=i686-pc-linux-gnu --host=i586-mingw32msvc \
   --enable-optimization --disable-CLI --with-wx-prefix=$WXMSWINSTALL 
 make
 cp -rf ../samples .
 mkdir $ALL_WIN_FILES $ALL_WIN_FILES/src $ALL_WIN_FILES/doc
 cp fityk.iss ../fityk.url ../COPYING ../AUTHORS ../TODO ../NEWS $ALL_WIN_FILES
 cp src/fityk.exe $ALL_WIN_FILES/src
 cp -r ../samples $ALL_WIN_FILES
 cp ../doc/fityk_tips.txt $ALL_WIN_FILES/doc
 if [ -a doc/fitykhelp.htb ]; then
	 unzip doc/fitykhelp.htb -d $ALL_WIN_FILES/doc
 else
	 unzip ../doc/fitykhelp.htb -d $ALL_WIN_FILES/doc
 fi
 # i had problems making hhp working under wine
 echo '"C:\Program Files\HTML Help Workshop\hhc.exe" doc\htmlhelp.hhp' \
					    >$ALL_WIN_FILES/build_help.cmd
 echo 'ren doc\htmlhelp.chm fitykhelp.chm' >>$ALL_WIN_FILES/build_help.cmd
 echo everything is in: `pwd`/$ALL_WIN_FILES
 

elif [ $1 -eq 7 ]; then
 echo uploading files to $TEMP_DOWNLOAD testing windows installer 
 scp $tarball_filename $TEMP_DOWNLOAD  
 scp $win_setup_filename $TEMP_DOWNLOAD   
 echo now ask other people to download it and test...
 

elif [ $1 -eq 8 ]; then
 echo  SF release
 echo uploading files...
 cp -f $MINGW_DIR/$ALL_WIN_FILES/Output/$win_setup_filename .
 curl -v -T $tarball_filename ftp://upload.sourceforge.net/incoming/ 
 curl -v -T $win_setup_filename ftp://upload.sourceforge.net/incoming/ 
 echo now go to:
 echo $SF_NEW_RELEASE
 echo and add release named: $version
 

elif [ $1 -eq 9 ]; then
 echo web announce, prepare for vim editing...
 scp $WEB_ANNOUNCE_DIR/$WEB_ANNOUNCE_FILE .
 sleep 2
 vi $WEB_ANNOUNCE_FILE
 scp $WEB_ANNOUNCE_FILE $WEB_ANNOUNCE_DIR
 
 
elif [ $1 -eq 10 ]; then
 echo FM announce
 echo TODO
 # freshmeat-submit
 
 
elif [ $1 -eq 11 ]; then
 echo cleaning everything and preparing normal working environment
 rm -rf $BUILD_DIR
 rm -rf $CVSTEST_DIR
 rm -rf $GCC2_DIR
 rm -rf $OLDWX_DIR
 make clean
 #./autogen.sh
 ./configure --enable-debug
 make
 
else
 echo unexpected step number: $1
fi

