.TH xyconv 1 "Oct 2009"
.SH NAME
xyconv \- a converter of files in formats supported by xylib
.SH SYNOPSIS
.br
.B xyconv
[options] input_file output_file
.br
.B xyconv
[options] [file]
.SH DESCRIPTION
\fIxyconv\fP is a simple utility that converts files in formats supported
by xylib into TSV (tab-separated-values) format.
.PP
Xylib library supports a subset of Vamas ISO14976 format, several formats
used for storing data from powder diffraction (pdCIF, Bruker RAW and UXD,
Philips RD and UDF, Sietronics Sieray CPI) and other niche formats,
typically containing 1D data from physical or chemical experiments.

.SH OPTIONS
For a full summary of options, run \fIxyconv \-h\fP.

.SH AUTHORS
Written by Marcin Wojdyr <wojdyr@gmail.com>.
